### ISSUE TITLE
RPF counts to TPM conversion

### ISSUE THREAD

**Issue by HiteshKore** [smithlabcode/ribotricer#108]
Hi Sanket, 
I want to generate TPM counts out of raw RPFs outputted from RiboTricer. I am using following link to convert raw counts into TPM.

https://www.rna-seqblog.com/rpkm-fpkm-and-tpm-clearly-explained/
Step followed: 

1.	Divided the read counts by the length of each transcript in kilobases. 
2.	Summed up all the RPK values in a sample and this number was divided by 1,000,000.
3.	Divided the RPK values by the “per million” scaling factor. 

I was wondering if I should divide the raw RFP count by ORF length instead of transcript length in step 1. What would be the right approach? Are there any standard packages to convert raw counts into TPM values?

Any help would be greatly appreciated.

_Originally posted by @HiteshKore in https://github.com/smithlabcode/ribotricer/issues/91#issuecomment-1019669699_

**Comment by saketkc** [comment]
The counts -> TPM approach is similar for RPFs as in standard RNA-seq. I would use the ORF length as the denominator here.

**Comment by HiteshKore** [comment]
Thanks  @saketkc
