### ISSUE TITLE
About the length of reads

### ISSUE THREAD

**Issue by lbwfff** [smithlabcode/ribotricer#115]
Hi, saketkc
I have a question, when using ribotricer to predict orfs, what is the interval of read lengths considered by ribotricer?
Thanks，
LeeLee

**Comment by saketkc** [comment]
It automatically determines the most informative read lengths to use (based on if the metagene distribution for a given read length exceeds the cutoff): https://github.com/smithlabcode/ribotricer/blob/master/ribotricer/detect_orfs.py#L360. The profiles are then merged by determine an appropriate offset that maximizes the cross-correlation.

You can override this behavior by providing a list of read lengths to use and their corresponding p-site offsets:
https://github.com/smithlabcode/ribotricer/blob/003a0199f63e1554238b9206131134d4931e2cf1/ribotricer/cli.py#L139
https://github.com/smithlabcode/ribotricer/blob/003a0199f63e1554238b9206131134d4931e2cf1/ribotricer/cli.py#L153

Feel free to reopen if you have any other questions.

**Comment by lbwfff** [comment]
> It automatically determines the most informative read lengths to use (based on if the metagene distribution for a given read length exceeds the cutoff): https://github.com/smithlabcode/ribotricer/blob/master/ribotricer/detect_orfs.py#L360. The profiles are then merged by determine an appropriate offset that maximizes the cross-correlation.
> 
> You can override this behavior by providing a list of read lengths to use and their corresponding p-site offsets:
> 
> https://github.com/smithlabcode/ribotricer/blob/003a0199f63e1554238b9206131134d4931e2cf1/ribotricer/cli.py#L139
> 
> 
> https://github.com/smithlabcode/ribotricer/blob/003a0199f63e1554238b9206131134d4931e2cf1/ribotricer/cli.py#L153
> 
> Feel free to reopen if you have any other questions.

Hi, saketkc

I understand that Ribotricer will Assessing the Periodicity of Read Length, but will Ribotricer assess all the read length in the BAM file? Even if it is far greater than or less than 30bp.

Thanks, leelee

**Comment by saketkc** [comment]
Yes
