### ISSUE TITLE
Option to include multimapping reads?

### ISSUE THREAD

**Issue by PVlasov93** [smithlabcode/ribotricer#125]
If I understand correctly, the program's default setting for handling multi-mapped reads is to disregard them entirely and only calculate translation behavior from single-mapped reads. 
Is there a setting that changes this?

**Comment by saketkc** [comment]
We currently do not support multimapping reads. I am also not sure how they should be handled given the requirement of having base-pair level resolution. Feel free to reopen if you have any follow up questions.
