### ISSUE TITLE
About definition of ORFs

### ISSUE THREAD

**Issue by Jiahuan90** [smithlabcode/ribotricer#130]
Hi, I find Ribotricer is really helpful for me to detect uORFs/dORFs on ribo-seq data. 
   
However, I have a question about super_uORFs and ORFs, I have read the manual carefully, what is the difference between super_uORFs and uORFs? I don't recognize the difference between the two definition. Could you give me an example?

Thank you for your kindly help!!

**Comment by saketkc** [comment]
`super_uORF` is the first uORF - most upstream of the CDS. `uORFs` are all remaining uORFs. Hope this helps, please feel free to reopen with any follow of questions.
