### ISSUE TITLE
about 3nt periodicity output

### ISSUE THREAD

**Issue by Jiahuan90** [smithlabcode/ribotricer#133]
Hi Saket,
Thanks for developing this great tool!

I have a question on 3nt periodicity:

I used ribotricer find many ORFs in lncRNAs. However, I found adjust parameter would give different number of ORFs on lncRNAs.

Therefore, I want to draw periodicity on some lncRNA's ORF to check if lncRNA's ORF have false positive.

I don't know how to use ribotricer to meet my requirement.

Thank you for your kindly help~

**Comment by saketkc** [comment]
Hello @Jiahuan90, thanks for the question. I have created a notebook to demonstrate how to plot ribotricer generated profiles: https://github.com/smithlabcode/ribotricer/blob/master/notebooks/Plotting_ribotricer_profile.ipynb

Feel free to reopen if you have any follow up questions. Thanks!

**Comment by Jiahuan90** [comment]
Hi @saketkc, thank you for your kindly help!

I've realized that column 18 ---- profile from *SRX219170_translating_ORFs.tsv are reads coverage of each nucleotide.

However, I have another question: I've carefully look through the manual, finding that, by default, ribotricer doesn't take read coverage into account when detect ORFs. The key element is the phase score.

I try my best to study the paper "Accurate detection of short and long active ORFs using Ribo-seq data", but still can't understand the concept of phase score.

I was wondering if it is possible to explain the concept of phase score?

Thank you again for your kindly help!!




Jiahuan He,  Ph.D.


State Key Laboratory of Medical Molecular Biology, 

Institute of Basic Medical Sciences,

Peking Union Medical  College & Chinese Academy of Medical Sciences,

Beijing,  P.R.China

e-mail: ***@***.***




At 2022-09-29 04:55:54, "Saket Choudhary" ***@***.***> wrote:

Hello @Jiahuan90, thanks for the question. I have created a notebook to demonstrate how to plot ribotricer generated profiles: https://github.com/smithlabcode/ribotricer/blob/master/notebooks/Plotting_ribotricer_profile.ipynb

Feel free to reopen if you have any follow up questions. Thanks!

**Comment by saketkc** [comment]
These slides might be helpful: https://saket-choudhary.me/pdfs/ribotricer_concept.pdf (there are transitions so ideall best viewed in slideshow mode) => The idea is to essentially calculate how often the profile exhibits the "high-low-low" pattern.
