### ISSUE TITLE
Trouble installing with bioconda [BUG]

### ISSUE THREAD

**Issue by ericmalekos** [smithlabcode/ribotricer#136]
* ribotricer version:
* Python version:
* Operating System: Ubuntu

### Description

When I try to install ribotricer through conda it is failing. I also tried with pip and it failed as well.  I tried this on both a server (CentOS) and my personal computer (Ubuntu) with the same result.

### What I Did

```
conda create -n ribotricer -c bioconda ribotricer
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          

UnsatisfiableError: 
```

**Comment by saketkc** [comment]
I am unable to reproduce this. Can you try? `conda create -n ribotricer PYTHON=3.7` followed by `conda activate ribotricer && pip install ribotricer`.

**Comment by ericmalekos** [comment]
This worked! Thanks.
