### ISSUE TITLE
Empty result in first step (Preparing candidate ORFs)

### ISSUE THREAD

**Issue by SuiyueWestlake** [smithlabcode/ribotricer#140]
Hi,

* ribotricer version:
* Python version:
* Operating System:

### Description

I'm trying to get the short ORFs of whole human genome. So I downloaded the gtf file from Ensembl database. And also the fasta file of cDNA and ncRNA sequence. It is reported some warnings like"Chromosome GL000220.1 does not appear in the fasta". And finally I got an empty result file. 

### What I Did
`ribotricer prepare-orfs --gtf Homo_sapiens.GRCh38.110.gtf --fasta Homo_sapiens.GRCh38.ncrna.fa --prefix ncrna_small_peptide --start_codons ATG,CTG,GTG,TTG`

### Output
<img width="1412" alt="image" src="https://github.com/smithlabcode/ribotricer/assets/109425008/653c4e79-85a0-47cd-996f-b1096630be73">

<img width="1919" alt="image" src="https://github.com/smithlabcode/ribotricer/assets/109425008/319f5a98-71df-442c-b2c6-c97f41fd3a0b">

Thank you so much for you help!

Best,
Yue

**Comment by saketkc** [comment]
You need to pass the genome fasta, not the cdna.

**Comment by SuiyueWestlake** [comment]
Thank you so much for your reply.

In my project, I'm trying to detect some unusual ORFs that may potentially can be translated to peptides. So I think this kind of sequence may exist in cDNA or ncRNA region. This is the reason why I submit the cDNA fasta file.

**Comment by saketkc** [comment]
Yes.

**Comment by SuiyueWestlake** [comment]
Thank you! 
I will try it now!
