### ISSUE TITLE
Translation of ORFs

### ISSUE THREAD

**Issue by SuiyueWestlake** [smithlabcode/ribotricer#142]
Hi,

I used ribotrice to detect a number of ORFs. And the following step of my research is to translate these ORFs to peptides. So I was wondering if there is a tool that you recommend to further translation based on the output format of ribotrice.

Thank you for your help!

Best,
Yue

**Comment by saketkc** [comment]
You can use the `orfs-seq` subcommand to generate the corresponding DNA or Protein sequences of the ORFs:


```
 $ ribotricer orfs-seq --help
Usage: ribotricer orfs-seq [OPTIONS]

  Generate sequence for ORFs in ribotricer's index

Options:
  --ribotricer_index TEXT  Path to the index file of ribotricer This file
                           should be generated using ribotricer prepare-orfs
                           [required]
  --fasta TEXT             Path to FASTA file  [required]
  --protein                Output protein sequence instead of nucleotide
  --saveto TEXT            Path to output file  [required]
  -h, --help               Show this message and exit.
```
