### ISSUE TITLE
I have confuse about the profile column from translating_ORFs.tsv

### ISSUE THREAD

**Issue by fork16** [smithlabcode/ribotricer#144]
Hi, thank you very much for providing this software. And I have a confuse about the profile column from translating_ORFs.tsv

Why most of the values in the column 'profile' is 0? And a little codon that is not 0, does these codons is just start codons? If not, a length of read has around 28nt, so there should be 9 codons, and all 9 codons in profile should have a value. Is there a problem with my understanding?

**Comment by saketkc** [comment]
translating_ORFs.tsv provides the profile of all the ORFs in your ribotricer index. The ORFs could be of varied length.
