### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by fork16** [smithlabcode/ribotricer#146]
* ribotricer version: 1.3.3
* Python version: 3.10.12
* Operating System: GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)

### Description
I have two sample to detect orfs. One is done but another gets following bug.

### What I Did

```

ribotricer detect-orfs --bam ${file} --ribotricer_index ${ribotricer_index_tsv} --prefix ${file/bam/} --report_all --phase_score_cutoff 0
Sep 14 10:25:03 ..... started ribotricer detect-orfs
Sep 14 10:25:03 ... started parsing ribotricer index file
Sep 14 10:25:07 ... started inferring experimental design                                                                               
Sep 14 10:25:07 ... started reading bam file
Sep 14 10:25:10 ... started plotting read length distribution                                                                           
Sep 14 10:25:10 ... started calculating metagene profiles. This may take a long time...
                                    
Sep 14 10:25:10 ... started plotting metagene profiles
Sep 14 10:25:10 ... started inferring P-site offsets
WARNING: no periodic read length found... using cutoff 0.0

```
The difference between the two files is not significant, but read counts of successful one is more than another one.
![image](https://github.com/smithlabcode/ribotricer/assets/74097067/25d1c2ec-bd50-4cb2-ac98-3db8d598163a)
![image](https://github.com/smithlabcode/ribotricer/assets/74097067/19235261-8944-42c7-9db4-d9fdd9047261)

Is this an error caused by the read counts?

**Comment by saketkc** [comment]
This is not a bug. Ribotricer could not find evidence for periodicity in any of the read lengths. You can lower the periodicity threshold and see if that helps.
