### ISSUE TITLE
About the read density in the output file

### ISSUE THREAD

**Issue by lbwfff** [smithlabcode/ribotricer#148]
Hi, saketkc

I would like to confirm the definition of the 'reads density' column in the final output file of Ribotricer. Are the 'reads' here not normalized, similar to ‘Counts’ in RNA-seq? 

Thanks,
LeeLee

**Comment by saketkc** [comment]
The read density is simply: `(number of uniquely mapped reads)/(orf length)`. I would recommend using DESeq2 or related tools for normalization of the counts matrix.
