### ISSUE TITLE
Unstranded Library

### ISSUE THREAD

**Issue by bshim181** [smithlabcode/ribotricer#149]
Hello, 

I am aware that Ribotricer infers strandedness of the protocol and determines whether it is forward or reverse stranded. I was wondering what happens if the protocol is unstranded? How would Ribotricer handle in this case? Thank you!

**Comment by saketkc** [comment]
By default, the protocol is set to `forward`: https://github.com/smithlabcode/ribotricer/blob/34bcf7f7c4a19e42b5225641e5eec638376d1eb2/ribotricer/infer_protocol.py#L108

If you have come across unstranded Ribo-seq datasets, I will be curious to know.
