### ISSUE TITLE
 Could not solve for environment specs: click-help-colors >=0.3 , which does not exist (perhaps a missing channel)

### ISSUE THREAD

**Issue by spencer411** [smithlabcode/ribotricer#150]
I get the following when attempting the conda install instructions:

conda create -n ribotricer_env -c bioconda ribotricer
Channels:
 - bioconda
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides click-help-colors >=0.3 needed by ribotricer-1.0.2-py36_0

Could not solve for environment specs
The following package could not be installed
└─ ribotricer is not installable because it requires
   └─ click-help-colors >=0.3 , which does not exist (perhaps a missing channel).

**Comment by saketkc** [comment]
`click-help-colors` is on conda-forge: https://anaconda.org/conda-forge/click-help-colors so additionally specifying `-c conda-forge` should solve it. I recommend setting the channel priority as recommended by bioconda: 

```bash
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
conda config --set channel_priority strict
```
