### ISSUE TITLE
Prepare ORFs step

### ISSUE THREAD

**Issue by bshim181** [smithlabcode/ribotricer#152]
I had a question regarding preparation of all candidate ORFs from annotated transcript regions. I was wondering why only 3 frame translation is conducted to pull out candidate ORF. If I am trying to generate a database of ORFs from my transcript targets of interest, does it make sense to do 6 frame translation to get all candidate ORFs?

**Comment by danielrebib** [comment]
No, because the "negative" three frames would mean your transcript is read from 3' to 5' direction, which doesn't occur to a processed mRNA. Given that you already know the strand of the parent transcript (as they are all annotated ENSTs), then you know the direction they must be read in.

**Comment by saketkc** [comment]
thanks @danielrebib! @bshim181 the index also takes GTF as an input which has the direction of translation for these genes (since these are annotated)
