### ISSUE TITLE
Control over minimum coverage + better error messages

### ISSUE THREAD

**Issue by pinin4fjords** [smithlabcode/ribotricer#154]
**Is your feature request related to a problem? Please describe.**

Minimum metagene coverage is essentially hard-coded, since a default value is set [here](https://github.com/smithlabcode/ribotricer/blob/34bcf7f7c4a19e42b5225641e5eec638376d1eb2/ribotricer/metagene.py#L124), and no interface to that value is provided when calling the function in places like [this](https://github.com/smithlabcode/ribotricer/blob/34bcf7f7c4a19e42b5225641e5eec638376d1eb2/ribotricer/detect_orfs.py#L419).

The result is that no reads are selected, and errors appear like:

```
WARNING: no periodic read length found... using cutoff 0.0
```

That doesn't really describe the issue- the problem is that no reads passed the coverage threshold. 

This also prevents operation in relatively low read counts, which might make sense scientifically, but makes the module hard to use in test scenarios (where scientific validity is not required). 

**Describe the solution you'd like**
Would you be amenable to a detect-orfs CLI parameter which controls this value? Happy to make a PR.  

There should also be an error triggered when all reads are removed in the coverage filter, to make it clear that periodicity is not the problem.

**Additional context**
Attempting to include ribotricer in the nf-core riboseq workflow.

**Comment by pinin4fjords** [comment]
Roughly like https://github.com/smithlabcode/ribotricer/pull/155 (whipped up in 10 mins, so just illustrating)

**Comment by saketkc** [comment]
Closed by #155
