### ISSUE TITLE
ORF Profile

### ISSUE THREAD

**Issue by bshim181** [smithlabcode/ribotricer#156]
Hello, 

I have been using Ribotricer in my project for quite a while now and I couldnt fully understand the part where ribotricer is agnostic the to the frame. Lot of statistical approaches to ORF prediction with RiboSeq data looks at reads that align to Frame 1. In the case below, It seems that reads covering this ORF belong to Frame 3. 

<img width="800" alt="Screenshot 2024-03-20 at 2 26 26 PM" src="https://github.com/smithlabcode/ribotricer/assets/53489568/3c287dd1-8d99-48ee-a751-1dd3ee58dbca">

Considering that Frame 1 reads align at the 5' end with the start codon, wouldnt frame 3 reads be considered as out of frame with the current ORF (or in frame with some ORF upstream)? Is 3nt periodicity or the high-low-low pattern sufficient to classify translation?

**Comment by saketkc** [comment]
Frame 1, Frame2, Frame 3 definitions are with respect to the start codon, so the 3-nt offset in this case is cyclic (can be tagged as Frame 1)
