### ISSUE TITLE
Peptide search from ORFs. 

### ISSUE THREAD

**Issue by bshim181** [smithlabcode/ribotricer#157]
This is a follow up question to issue #156. 

I have understood the aspect of frames being cyclic in the read profile visualization.

Currently, I am aiming to do peptide search from these ORFs. In the case where we see Frame 3 periodicity for a specific ORF, Can we still use translated peptide sequences from _"ribotricer orfs-seq"_ output"? Since ribotricer do not identify TIS, this implies that translation did not start at the start codon for this ORF, but possibly upstream. Should we look at peptide sequence translated at Frame 3 for that ORF and not Frame 1? My understanding might be flawed so correct me if I am wrong with this assumption.

**Comment by saketkc** [comment]
Responded over email.
