### ISSUE TITLE
Question about handling of non-unique alignments

### ISSUE THREAD

**Issue by mosi223** [smithlabcode/ribotricer#159]
Dear Ribotricer developers,

According to the documentation, it is recommended to include outFilterMultimapNmax 1 parameter in STAR alignment to exclude non-unique alignments and reduce noise for downstream analyses.

In case of default outFilterMultimapNmax 10 setting, how does Ribotricer handle non-unique alignments? Are they included in ORF detection? Does Ribotricer differentiate between primary and secondary alignment flags when dealing with multi-mapped reads?

Thank you very much!

**Comment by saketkc** [comment]
Thanks for your question. We only use uniquely mapping reads (https://github.com/smithlabcode/ribotricer/blob/7a7d8e2a95a55466f5d2fad3219533583532b804/ribotricer/bam.py#L78C22-L78C42). The recommendation of switching on `outFilterMultmapNmax` to 1 is to ensure the downstream tasks are quicker (no multimapping -> smaller bam). but we perform filtering inside anyway.

 Hope it helps!

**Comment by mosi223** [comment]
Great! Thank you very much for the speedy answer!

**Comment by punching-samuel** [comment]
> Thanks for your question. We only use uniquely mapping reads (https://github.com/smithlabcode/ribotricer/blob/7a7d8e2a95a55466f5d2fad3219533583532b804/ribotricer/bam.py#L78C22-L78C42). The recommendation of switching on `outFilterMultmapNmax` to 1 is to ensure the downstream tasks are quicker (no multimapping -> smaller bam). but we perform filtering inside anyway.
> 
> Hope it helps!

What is your opinion on the origin of multi-mapped reads in RiboSeq? Do RiboSeq analyses typically consider only unique-mapped reads? 
It‘s my first time to analyze the riboseq data. I'll appreciate it if you resolve my confusion.

Thank you!
Sammi
