### ISSUE TITLE
Question about Multi-Mappers

### ISSUE THREAD

**Issue by singhbhavya** [smithlabcode/ribotricer#160]
Hi there,

I've come to understand that the program does not handle multi-mappers. For our purpose of looking at TE elements (which often have multimapping due to very similar reads), we need to allow for this. If the BAM  files were generated with multi-mappers, can they still be run through the program? Does RiboTricer pick the alignment with the highest quality & mapping score?

**Comment by saketkc** [comment]
Yes, they can still be run through the program. The recommendation for only keeping unique reads is for computational efficiency (larger bam -> more time to parse). We only use uniquely mapping reads (tracking the sam flags) for all downstream processing. Hope this helps!
