### ISSUE TITLE
Handling read-level P-Site offsets 

### ISSUE THREAD

**Issue by mosi223** [smithlabcode/ribotricer#162]
Dear @saketkc,

I am working on assigning P-Site offsets using the tool [PSite](https://github.com/gxelab/psite), which infers offsets for each individual read as opposed to grouping reads based on read lengths.

By default, PSite builds the offset information directly into BAM files via an additional tag, but those can be coerced into a text format if needed. Could you recommend a way to use these read-level offsets for determining translating ORFs in Ribotricer or would it require significant changes to the Ribotricer's codebase?

Thank you very much!

**Comment by saketkc** [comment]
Hi @mosi223 , thanks for your question. This is possible by specifying the `--read_lengths`  and `--psite_offsets` [arguments](https://github.com/smithlabcode/ribotricer/blob/7a7d8e2a95a55466f5d2fad3219533583532b804/ribotricer/cli.py#L249). For example, 

```bash
ribotricer detec_orfs --read_lengths 28.29,30,31 --psite_offset 10,11,12
```

**Comment by mosi223** [comment]
Hi @saketkc ! Thanks for getting back so quickly! But does this not specify the offsets based on read lengths? What I would like to do is to specify offsets for each individual read, i.e., it's possible that reads of the same length will have a difference offset.

**Comment by saketkc** [comment]
This is exactly what it does. Here is the documentation of the code I had previously linked to.

```
   "Comma separated P-site offsets for each read length "
        "matching the read lengths provided.\n"
        "If not provided, reads from different read lengths will be "
        "automatically aligned using cross-correlation"

```

**Comment by saketkc** [comment]
Unfortunately this is currently not possible with ribotricer. I am also not sure I have seen a convincing argument for read level adjustment.

**Comment by mosi223** [comment]
Hi @saketkc ! Thank you for the response! There's is some evidence that read-level P-site offsets increase accuracy of ORF detection. But I also understand that this is a very new development.

**Comment by ericmalekos** [comment]
@mosi223 Are there publications on offsets for individual reads? Could you please share, I would be very interested to see this

**Comment by mosi223** [comment]
Hi @ericmalekos ,

Thanks for following up!

There aren't a lot of publications as it is a very new technique. So far, the only method I know that does this is [PSite](https://github.com/gxelab/psite). It's really new but there's a [pre-print](https://www.biorxiv.org/content/10.1101/2023.06.27.546788v1). It's based on a ML approach and predicts offsets for individual reads. The offsets are then built into the alignment files for downstream use. PSite has been shown to be compatible with RiboCode and Ribo-TISH. From what the authors show and also what I've seen so far, it tends to improve the ORF detection results, particularly for samples with low sequencing depth and thus low initial coverage.
