### ISSUE TITLE
TYPICAL_OFFSET = 12 

### ISSUE THREAD

**Issue by fenghuawei** [smithlabcode/ribotricer#163]
I want to know whether TYPICAL_OFFSET  will have an effect on the result.
I do not know whether my data have a typical_offset of 12

**Comment by saketkc** [comment]
By default ribotricer determines the appropriate offset for each read length:

```
6. Align metagene profiles
If the P-site offsets are not provided, this step will use cross-correlation to find out the relative offsets between different read lengths
Output: {OUTPUT_PREFIX}_psite_offsets.txt


```
