### ISSUE TITLE
Can ribotricer output ORF sequence like AAATTTCCCCGGG

### ISSUE THREAD

**Issue by hawkwoodpps** [smithlabcode/ribotricer#165]
Hello

I use the workflow as the following:
ribotricer prepare-orfs --gtf xxxxxxxxx.gtf \
 --fasta xxxxxxx.fa \
 --prefix xxxxxxx
 
 ribotricer detect-orfs --bam xxxxxxxx.bam \
 --ribotricer_index xxxxxxxxx.tsv \
--phase_score_cutoff 0.330 \
--report_all \
 --prefix xxxxxxxxxx
 
 in the output xxxxx.tsv, how can I know the orf sequence

**Comment by saketkc** [comment]
Thanks for your question? To obtain nucleotide sequence associated with ORFs in ribotricer index, you can use the `orfs-seq` command:

```bash
ribotricer orfs-seq --ribotricer_index <path_to_ribotricer_index> --fasta <fasta>
```
You can run `ribotricer orfs-seq --help` to see other options.

Hope this helps, feel free to reopen with any follow up questions.

**Comment by hawkwoodpps** [comment]
Thank you 

What is the difference between `orfs-seq` and `detect-orfs`?

**Comment by saketkc** [comment]
orfs-seq gives you just a file of orf sequences.

**Comment by hawkwoodpps** [comment]
Is there any option like `phase_score_cutoff` in the `orfs-seq`?

**Comment by saketkc** [comment]
I would encourage you to run the program. The  README of this repository and `--help` option for each subcommand is pretty comprehensive.

**Comment by hawkwoodpps** [comment]
ok
