### ISSUE TITLE
TI Seq

### ISSUE THREAD

**Issue by bshim181** [smithlabcode/ribotricer#166]
Hello, 

I have been trying to validate the list of ORFs predicted from ribotricer with Translation initiation sequencing dataset. 
I am inputting the list of non-canonical ORF predictions to Ribotish and predicting TI Seq validated ORFs. 
It seems like within Ribotish, it cannot process ORFs that span introns of the transcript (throwing an error)
I was wondering if the ORF candidates generated from Ribotricer contains non-canonical ORFs that start in intron or end in intron. 
Thank you!

**Comment by saketkc** [comment]
We do not use introns: https://github.com/smithlabcode/ribotricer/blob/7a7d8e2a95a55466f5d2fad3219533583532b804/ribotricer/gtf.py#L127

but if the gtf has a discordant definition of intron/exon, that might result in a bleed through.
