### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mjim18** [smithlabcode/ribotricer#4]
* ribotricer version: 1.3.2
* Python version: 3.7
* Operating System: linux

### Description

I just downloaded and installed ribotricer using `conda install ribotricer`. My computer recognizes that it is installed and is in the correct place when I call `which ribotricer`. However, trying to get more info or use the ribotricer commands leads to this error. Is is something to do with pysam being installed incorrectly?

### What I Did

```
$ ribotricer
/homes/jimmx/miniconda3/lib/python3.7/site-packages/tqdm/std.py:668: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  from pandas import Panel
Traceback (most recent call last):
  File "/homes/jimmx/miniconda3/bin/ribotricer", line 33, in <module>
    sys.exit(load_entry_point('ribotricer==1.3.2', 'console_scripts', 'ribotricer')())
  File "/homes/jimmx/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/homes/jimmx/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2861, in load_entry_point
    return ep.load()
  File "/homes/jimmx/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2461, in load
    return self.resolve()
  File "/homes/jimmx/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2467, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/homes/jimmx/miniconda3/lib/python3.7/site-packages/ribotricer/cli.py", line 31, in <module>
    from .detect_orfs import detect_orfs
  File "/homes/jimmx/miniconda3/lib/python3.7/site-packages/ribotricer/detect_orfs.py", line 22, in <module>
    from .infer_protocol import infer_protocol
  File "/homes/jimmx/miniconda3/lib/python3.7/site-packages/ribotricer/infer_protocol.py", line 19, in <module>
    import pysam
  File "/homes/jimmx/.local/lib/python3.7/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
  File "pysam/libchtslib.pyx", line 1, in init pysam.libchtslib
ImportError: libchtslib.cpython-37m-x86_64-linux-gnu.so: cannot open shared object file: No such file or directory
```

**Comment by saketkc** [comment]
Hi @mjim18, Thanks for the bug report and trying ribotricer. This seems to be arising from the conda environment (which I assume is the default environment in your case).

We recommend that `ribotricer` be installed in a separate (clean) environment:
```
> conda create -n ribotricer_conda ribotricer
> conda activate ribotricer_conda
> ribotricer --help
```
Please let me know if you face any issues running `ribotricer` through its own environment.

**Comment by mjim18** [comment]
Hi @saketkc, thanks for your advice but even if use ribotricer in the exact way you showed, I get the same error.

**Comment by saketkc** [comment]
Can you paste the output of

```
> conda activate ribotricer_conda && conda env export
```

**Comment by mjim18** [comment]
`
> conda activate conda_ribotricer && conda env export
bash: syntax error near unexpected token `conda'
(base) jimmx@----:/sc/wo/home/jimmx> conda activate conda_ribotricer && conda env export
name: conda_ribotricer
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - bzip2=1.0.8=h516909a_2
  - ca-certificates=2020.6.20=hecda079_0
  - certifi=2020.6.20=py37hc8dfbb8_0
  - click=7.1.2=pyh9f0ad1d_0
  - click-help-colors=0.8=pyh8c360ce_0
  - cycler=0.10.0=py_2
  - freetype=2.10.2=he06d7ca_0
  - icu=64.2=he1b5a44_1
  - kiwisolver=1.2.0=py37h99015e2_0
  - krb5=1.17.1=hfafb76e_1
  - ld_impl_linux-64=2.34=h53a641e_5
  - libblas=3.8.0=16_openblas
  - libcblas=3.8.0=16_openblas
  - libcurl=7.71.0=hcdd3856_0
  - libdeflate=1.6=h516909a_0
  - libedit=3.1.20191231=h46ee950_0
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-ng=9.2.0=h24d8f2e_2
  - libgfortran-ng=7.5.0=hdf63c60_6
  - liblapack=3.8.0=16_openblas
  - libopenblas=0.3.9=h5ec1e0e_0
  - libpng=1.6.37=hed695b0_1
  - libssh2=1.9.0=hab1572f_2
  - libstdcxx-ng=9.2.0=hdf63c60_2
  - llvm-openmp=10.0.0=hc9558a2_0
  - matplotlib-base=3.2.2=py37h30547a4_0
  - ncurses=6.1=hf484d3e_1002
  - numpy=1.18.5=py37h8960a57_0
  - openssl=1.1.1g=h516909a_0
  - pandas=1.0.5=py37h0da4684_0
  - pip=20.1.1=py_1
  - pyfaidx=0.5.9=pyh4c3bd37_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pysam=0.16.0.1=py37hc501bad_0
  - python=3.7.6=cpython_h8356626_6
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytz=2020.1=pyh9f0ad1d_0
  - quicksect=0.2.2=py37h8f50634_2
  - readline=8.0=hf8c457e_0
  - ribotricer=1.3.2=py_0
  - scipy=1.4.1=py37ha3d9a3c_3
  - setuptools=47.3.1=py37hc8dfbb8_0
  - six=1.15.0=pyh9f0ad1d_0
  - sqlite=3.32.3=hcee41ef_0
  - tk=8.6.10=hed695b0_0
  - tornado=6.0.4=py37h8f50634_1
  - tqdm=4.46.1=pyh9f0ad1d_0
  - wheel=0.34.2=py_1
  - xz=5.2.5=h516909a_0
  - zlib=1.2.11=h516909a_1006
prefix: /homes/jimmx/miniconda3/envs/conda_ribotricer

`

**Comment by saketkc** [comment]
Thanks @mjim18, that's helpful. It's the same as mine. Can you also copy the log of 

> conda activate conda_ribotricer && ribotricer --help

**Comment by mjim18** [comment]
Thanks @saketkc for your help. Here's some more info:

$ conda activate conda_ribotricer && ribotricer --help

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.

**Comment by mjim18** [comment]
When I try 'conda init bash', my terminal just says that no changes were made. Same for powershell.

**Comment by saketkc** [comment]
Thanks @mjim18! It appears you are using an older version of conda that does not recognize `conda activate`. So the command will use `source activate`. Can you paste the output of 

```
source activate conda_ribotricer && ribotricer --help
```

**Comment by mjim18** [comment]
Here is the error @saketkc:

> source activate conda_ribotricer $$ ribotricer --help
bash: syntax error near unexpected token `source'
(conda_ribotricer) jimmx@----:/sc/wo/home/jimmx> source activate conda_ribotricer && ribotricer --help
/homes/jimmx/miniconda3/envs/conda_ribotricer/lib/python3.7/site-packages/tqdm/std.py:668: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  from pandas import Panel
Traceback (most recent call last):
  File "/homes/jimmx/miniconda3/envs/conda_ribotricer/bin/ribotricer", line 6, in <module>
    from ribotricer.cli import cli
  File "/homes/jimmx/miniconda3/envs/conda_ribotricer/lib/python3.7/site-packages/ribotricer/cli.py", line 31, in <module>
    from .detect_orfs import detect_orfs
  File "/homes/jimmx/miniconda3/envs/conda_ribotricer/lib/python3.7/site-packages/ribotricer/detect_orfs.py", line 22, in <module>
    from .infer_protocol import infer_protocol
  File "/homes/jimmx/miniconda3/envs/conda_ribotricer/lib/python3.7/site-packages/ribotricer/infer_protocol.py", line 19, in <module>
    import pysam
  File "/homes/jimmx/.local/lib/python3.7/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
  File "pysam/libchtslib.pyx", line 1, in init pysam.libchtslib
ImportError: libchtslib.cpython-37m-x86_64-linux-gnu.so: cannot open shared object file: No such file or directory

**Comment by saketkc** [comment]
Thanks @mjim18 for the log and being patient. You have `pysam` installed locally:
`/homes/jimmx/.local/lib/python3.7/site-packages/pysam/init.py` which was likely installed through `pip`. 

This is causing it to conflict it with the `conda` environment. Conda installs packages to the `envs` directory. For example, the correct `pysam` should be at `/homes/jimmx/miniconda3/envs/conda_ribotricer/lib/python3.7/site-packages/pysam`. 

I am not sure if this would help, but you can try getting rid of the local install of `pysam`:

```
source deactivate && pip uninstall pysam
```

A note of caution - this would make any other packages that rely on your local `pysam` unusable. But you can create a separate environment for those packages.

**Comment by mjim18** [comment]
@saketkc It works now. Thank you very much for your help!

**Comment by saketkc** [comment]
Thanks! Let me know if you have any questions!
