### ISSUE TITLE
Can ribotricer infer start codon position?

### ISSUE THREAD

**Issue by freeedog** [smithlabcode/ribotricer#45]

**Comment by saketkc** [comment]
Hi,

Just to elaborate on your question, you probably mean if ribotricer can detect translation initiation sites.

Ribotricer uses a collection of ORFs (defined by presence of an in-frame start and stop codons) to look for periodicity. It is possible that some of these ORFs are overlapping, and it is able to find periodicity in all of them - in which case we do not where translation was initiated. 

To overcome this limitation, we require more information, for example a different inhibitor that selectively arrests initiating ribosomes [1].

I hope that answers your question. Feel free to reopen if I misunderstood your question.

[1] https://www.nature.com/articles/s41467-017-01981-8

**Comment by freeedog** [comment]
Hi,

I mean that there is some hint of where tranlation initiated even in normal Riob-seq without special inhibitor.
For example, well can tell the translation start site in the following situation (set both CTG and ATG as candidate start codon):

![image](https://user-images.githubusercontent.com/33932424/136640142-69666653-ee52-46a1-8048-845822191692.png)
