### ISSUE TITLE
Output format question

### ISSUE THREAD

**Issue by mjim18** [smithlabcode/ribotricer#5]
Hi, 

The output format for the ORF ID is: ENST00000327044.7_944672_945119_192. The first part is the transcript ID, while the last the length of the sORF. What are the middle two numbers?

Thanks!

**Comment by saketkc** [comment]
`ENST00000327044.7_944672_945119_192`:


`ENST00000327044.7`: transcript id
`944672`: Genomic location where this ORF starts 
`945119`: Genomic location where this ORF ends
`192`: Total nucleotides in this ORF

Genomic locations are indicated for the chromosome they are in (`chrom` column).
