### ISSUE TITLE
Ribotricer with replicates

### ISSUE THREAD

**Issue by saketkc** [smithlabcode/ribotricer#54]
Hello, 

I know this issue is closed, but seemed like an appropriate place to asks these questions. 

I have multiple replicates of 3 different riboseq type (4 reps for 2 experimental conditions for chx, harringtonine and no drug treated riboseq). 

What would be the optimum strategy for analysis using Ribotricer? Pool all samples, pool the 3 different riboseq types for each replicate, or run each sample individually? 

Thanks,
Colin

_Originally posted by @colin986 in https://github.com/smithlabcode/ribotricer/issues/46#issuecomment-831416396_

**Comment by saketkc** [comment]
> I have multiple replicates of 3 different riboseq type (4 reps for 2 experimental conditions for chx, harringtonine and no drug treated riboseq).
What would be the optimum strategy for analysis using Ribotricer? Pool all samples, pool the 3 different riboseq types for each replicate, or run each sample individually?

Given you have replicates, it is best that they are treated as such for all downstream tasks. The workflow I recommend is:

- Run ribotricer on each replicate per condition separately
- Investigate the periodicity (you can use the output tsv or the pdf plots generated by ribotricer)

In principle, pooling will help boost your signal to noise ratio (SNR), but you will loose the "replicability". But it depends on what your end goal is. If you want to, for example identify pausing sites, or differential translation, you would need replicates. If you want to identify rare uORF translation, it would also make more sense to have replicates. You can use pooling to demonstrate a rare event (which is otherwise consistent across replicates but is not as pronounced because of low SNR).

Hope this helps! Let me know if you have any other questions.

**Comment by saketkc** [comment]
Also, please feel free to reopen with any follow up questions.

**Comment by colin986** [comment]
thanks for the advice!
