### ISSUE TITLE
Could this program to show summary 3 nt periodicity for specific RF nt

### ISSUE THREAD

**Issue by cornecu** [smithlabcode/ribotricer#9]
1. This program is so efficient and I used it to run my data very smoothly. How can I use package to summary 3 nt periodicity for specific RF length like 32 nt, 31 nt in my data. I know the metagene report give it but is there any way to summarize 3 nt periodicity for any specific RF length? 

If any report from these pipeline will give the direction, Could you give me some indication about that? 

2. for phase score cutoff, I USE my maize data, do I need to just use my own data from Riboseq and RNAseq to determine or Do I need to download all the maize Riboseq data to run and get one phase score?

Thank you so much.

**Comment by saketkc** [comment]
> I know the metagene report give it but is there any way to summarize 3 nt periodicity for any specific RF length?

You can use pandas to do so using the `metagene_profiles_5p.tsv` file outputted from [ribotricer](https://github.com/smithlabcode/ribotricer#detecting-translating-orfs):

```python
import pandas as pd
metagene = pd.read_csv("./ribotricer_results/metagene_profiles_5p.tsv", sep="\t").set_index("fragment_length")
metagene[["phase_score"]]
	phase_score
fragment_length	
20	0.375490
21	0.305324
22	0.085639
23	0.423339
24	0.297982
25	0.197412
26	0.515173
27	0.253958
28	0.712790
29	0.909565
30	0.851510
31	0.528801
```

> for phase score cutoff, I USE my maize data, do I need to just use my own data from Riboseq and RNAseq to determine or Do I need to download all the maize Riboseq data to run and get one phase score?

I would strongly recommend that you determine an optimal phase score cutoff for your own data by using say one replicate of your Ribo-seq and a RNA-seq sample as explained in the [instructions](https://github.com/smithlabcode/ribotricer#learning-cutoff-empirically-from-data). Using the default cutoff of `0.43` will give you conservative estimate of regions under active translation.

**Comment by cornecu** [comment]
Thank you so much. I really appreciate that you take time to answer questions.

So this ### 
import pandas as pd
metagene = pd.read_csv("./ribotricer_results/metagene_profiles_5p.tsv", sep="\t").set_index("fragment_length")
metagene[["phase_score"]]
	phase_score
fragment_length	
20	0.375490
21	0.305324
22	0.085639
23	0.423339
24	0.297982
25	0.197412
26	0.515173
27	0.253958
28	0.712790
29	0.909565
30	0.851510
31	0.528801

It seems this will give  the phase score. 

I am asking how to calculate the read count for 3 nt periodicity for all specific RF length. So I still need to use output file metagene_profiles_5p.tsv but to use profile column of this TSV file, right?? To summarize the read count for frame 0, frame1, and frame2 for one specific RF length? Yes?

**Comment by saketkc** [comment]
> I am asking how to calculate the read count for 3 nt periodicity for all specific RF length. So I still need to use output file metagene_profiles_5p.tsv but to use profile column of this TSV file, right?? To summarize the read count for frame 0, frame1, and frame2 for one specific RF length? Yes?

That's correct. However, that column gives a metagene summary using mean counts normalized by the mean coverage over say 120 nt (depending on the length of the metagene profile). We use the same summary to generate metagene plots (which are outputted as pdfs). 

If you are looking for profile for  individual ORFs, they are in the `translating_ORFs.tsv` file. I hope that helps, let me know if there are any questions.

**Comment by cornecu** [comment]
Thank you so much for your help and time. I will look into it.
