### ISSUE TITLE
Confusion about orf information

### ISSUE THREAD

**Issue by lbwfff** [smithlabcode/ribotricer#92]
Hi, saketkc
Excuse me again, I am a little confused about the orf information given by ribotricer. I found that the length of some orf is not an integer multiple of 3. For example, the following line: 
`ENST00000600966.1_58350594_58353129_917 | annotated | translating | 0.616830824 | 2987 | 917 | 214 | 0.701639 | 9.793443`
I don't quite understand such an orf, why does this happen?
Thanks，
LeeLee

**Comment by annebresciani** [comment]
Hi I had the same issue with Ensembl GTF GRCh38 v.104. 
Here is one example:
ENST00000646156_8868027_8871900_100     annotated       ENST00000646156 protein_coding  ENSG00000074800 ENO1    protein_coding  1       -       ATG     8868027-8868057,8870452-8870510,8871891-8871900
Thanks, 
Anne

**Comment by polklin** [comment]
Here are the files I am using to do the ORF preparation with Ribotricer:

I am using hg19 genome: https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_19/

- `fasta_file` : [GRCh37.p13.genome.fa.gz](https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_19/GRCh37.p13.genome.fa.gz)

- `gtf_file` : [gencode.v19.annotation.gtf.gz](https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_19/gencode.v19.annotation.gtf.gz)

The command :
```bash
ribotricer prepare-orfs --gtf gtf_file\
                                         --fasta fasta_file \
                                         --prefix $PROJECT_DIR/ \
                                         --min_orf_length 30 \
                                         --start_codons ATG,CTG,GTG
```

I tried with and without `--longest`, I have the problem in both cases

**Comment by polklin** [comment]
I have tried with latest GENCODE human GTF and fasta file (v42):

```bash
wget https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_42/GRCh38.p13.genome.fa.gz
wget https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_42/gencode.v42.annotation.gtf.gz
```

I still notice 12,031 ORF candidates with a length non multiple of 3.
They are all coming from `annotated` CDS.

Here is one example:
- ORF_id = `ENST00000480643.1_1091500_1091543_44`
- gene_name = `C1orf159`
- strand = `-`
- `chr1`
- start_codon = `ATG` 

Here is a screenshot taken from IGV.

![image](https://user-images.githubusercontent.com/25035705/233145428-d90930f4-a558-4adc-aa88-4e4fb95be4a7.png)

**Comment by saketkc** [comment]
Thanks for bumping this issue, I will take a look.

**Comment by polklin** [comment]
Hi @saketkc,

Did you have a chance to have a look ? Let me know if I can provide any additional useful information.

Best,
Paul

**Comment by saketkc** [comment]
Thanks for the reminder @polklin. I unfortunately haven't had a chance to take a look - I will take a look in the next couple of days.

**Comment by saketkc** [comment]
Hi @polklin, I finally had a chance to look and the explaination for your observation is simpler than I had first imagined.

This is the annotated CDS for the ENST00000480643.1 transcript:

```
chr1	HAVANA	CDS	1091500	1091543	.	-	0	gene_id "ENSG00000131591.18"; transcript_id "ENST00000480643.1"; gene_type "protein_coding"; gene_name "C1orf159"; transcript_type "protein_coding"; transcript_name "C1orf159-217"; exon_number 6; exon_id "ENSE00001952624.1"; level 2; protein_id "ENSP00000464657.1"; transcript_support_level "4"; hgnc_id "HGNC:26062"; tag "mRNA_end_NF"; tag "cds_end_NF"; havana_gene "OTTHUMG00000000745.9"; havana_transcript "OTTHUMT00000327126.3";

```

When performing ORF search, ribotricer treats CDS at their face value. i.e. if a particular region is annotated as CDS in the GTF, it does not perform de-novo search (based on the start and stop codons provided). In this case the 43nt long ORF is annotated as a CDS and hence the output. Hope this helps. Please let me know if you have any other questions.

**Comment by polklin** [comment]
Hello @saketkc, thank you very much for your investigation. 

I'll check few other weird examples I noticed when generating candidate ORFs and keep you posted if I have other questions
